[theme]
mode = "dark"
shell_mode = "follow"
source = "wallpaper"
wallpaper_scheme = "dysfunctional"
# pure_black_dark = true

[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = [
  "gtk",
  "kcolorscheme",
  "qt",
  "starship",
  "niri",
  "cava",
  "foot"
]
community_ids = [
  "fzf",
  "pywalfox",
  "konsole"
]
