[bar]
order = ["main"]

[bar.default]
position = "top"
radius = 12
margin_ends = 0
concave_edge_corners = false
widget_spacing = 6
capsule = true

start = ["workspaces", "group:resources", "group:net", "media"]
center = ["clock", "control-center"]
end = ["tray", "notifications", "clipboard", "network", "bluetooth", "volume", "battery", "settings", "session"]

[bar.default.actions]
middle = "none"

[[bar.default.capsule_group]]
id = "resources"
members = ["cpu", "ram"]
accordion = false
widget_spacing = 10
padding = 10

[[bar.default.capsule_group]]
id = "net"
members = ["net-download", "net-upload"]

[widget.cpu]
type = "sysmon"
stat = "cpu_usage"
interactive = false

[widget.ram]
type = "sysmon"
stat = "ram_used"
interactive = false

[widget.net-download]
type = "sysmon"
stat = "net_rx"
network_speed_unit = "auto"
network_speed_compact = true
interactive = false

[widget.net-upload]
type = "sysmon"
stat = "net_tx"
network_speed_unit = "auto"
network_speed_compact = true
interactive = false

[widget.settings]
glyph = "settings"

[widget.clock]
format = "{:%F} {:%H:%M}"
